### ISSUE TITLE
Swarm Example

### ISSUE THREAD

**Issue by BaddMann** [learnweb/docker-opencast#13]
Not Really an Issue. More of a question.

Have you guys tried the new Swarm capabilities of Docker with opencast?
I'm easily overpowering my test iMac with opencast's requirements and would like to scale it out to my other test iMacs. I could use the opencast model and will eventually use it for sure, but I was wondering how the new Swarm capabilities built into Docker would work out.

Any examples?

**Comment by mtneug** [comment]
We did not test the Opencast images with Docker Swarm. Also I only tried out Docker Swarm when it was still relative young, however I'm pretty sure that our compose files will work out of the box assuming a properly set up cluster. Since Docker Swarm is a transparent layer, you can use the same `docker-compose` commands. The only change is that for each container you have to specify resource constraints in the compose file.

**Comment by mtneug** [comment]
You would also have to adjust the hostnames (e.g. put them in one network => Docker will resolve the container name with DNS). We will probably add more documentation for different Docker orchestrators when we find the time. For now, I will close this issue.
